export const SET_FEEDS = "SET_FEEDS";
export const SET_HOME_USER = "SET_HOME_USER";
export const UPDATE_HOME_DATA = "UPDATE_HOME_DATA";
export const LOGIN_USER = "LOGIN_USER";
export const SET_PLAY = "SET_PLAY";
export const SUBSCRIBE_FEED = "SUBSCRIBE_FEED";
export const MODIFY_FEED = "MODIFY_FEED";
export const CLEAR_SUBSCRIBE = "CLEAR_SUBSCRIBE";
export const SET_LOADING = "SET_LOADING";
export const SHOW_STORIES_HEADER = "SHOW_STORIES_HEADER";

export const SET_PENDING_STORY = "SET_PENDING_STORY"
export const TOGGLE_SUSCRIBE_SCREEN = "TOGGLE_SUSCRIBE_SCREEN"
export const SET_CURRENT_FEED = "SET_CURRENT_FEED"
export const SET_SEEN = "SET_SEEN"